# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Regularized matrix and tensor decompositions. Models, algorithms and implementation.
author: Jeremy E. Cohen
logo: cube_on_dico_page.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force # cache
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - all_refs.bib #todo fuse with others
  - HDR.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cohenjer/HDR
  #path_to_book: manuscript  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  extra_extensions:
    - sphinx_proof

html:
  use_repository_button: true
  # Use Hypothesis for book reviews
  comments:
    hypothesis: true

# Make the cells runable online??
launch_buttons:
  thebe: true
  notebook_interface: "classic" # jupyterlab"  # or "classic"
  #binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)


# ---------- Github settings ------------
name: deploy-book

# Run this when the master or main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    - name: cache executed notebooks
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2