# For conda and mamba, requirements.txt contains pip installed packages
# A voir si ca marche bien avec binder, pour l'instant ca build mais ca launch pas.
# disabled pour le moment

name: hdr_auto
channels:
  - conda-forge
dependencies:
  - python==3.11
  - numpy
  - matplotlib
  - plotly
  - pip
  - sphinx
  - jupyter
  - jupyter-book
  - jupytext
  - pip:
    - -r requirements.txt 


